In [20]:
import numpy as np

In [21]:
# 1.a) Create a null vector of size 10 but the fith value which is 1
a = np.zeros((10))
a[[4]] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [22]:
# 1.b. Create a vector with values ranging from 10 to 49
b = np.arange(10, 50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [23]:
#1.c. Reverse a vector (first element becomes last) - Let's do it with b, for example
c = b[::-1]
# An alternative solution is:
c = np.flip(b)
c

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [24]:
# 1.d. Create a 3x3 matrix with values ranging from 0 to 8
d = np.arange(0, 9).reshape(3,3)
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
# 1.e. Find indices of non-zero elements from [1,2,0,0,4,0]
e = [1,2,0,0,4,0]
eanswer = np.asarray(e).nonzero()
eanswer

(array([0, 1, 4]),)

In [26]:
# 1.f. Create a random vector of size 30 and find the mean value
f = np.random.rand(30) # to make the values within a certain interval I can use >> p.random.uniform(low=, high=, size=())
print(f.mean())

0.44442649480809454


In [27]:
# 1.g. Create a 2d array with 1 on the border and 0 inside.
g = np.zeros(49).reshape(7,7)
g[::(len(g)-1)] = 1
g[:,0] = 1
g[:,(len(g)-1)] = 1
g

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [28]:
# 1.h. Create a 8x8 matrix and fill it with a checkerboard pattern
h = np.zeros(64).reshape(8,8)
h[1::2,::2] = 1
h[::2,1::2] = 1
h

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [29]:
# 1.i. Create a checkerboard 8x8 matrix using the tile function
h = np.array([0, 1, 0, 1, 0, 1, 0, 1])
h2 = np.array([1, 0, 1, 0, 1, 0, 1, 0])
h3 = np.concatenate((h2,h)).reshape(2,8)
h3 = np.tile(h3, (4,1))
h3

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [30]:
# 1.j. Given a 1D array, negate all elements which are between 3 and 8, in place
j = np.full(15, fill_value=6)
j[3:7] *= -1
print(j)

[ 6  6  6 -6 -6 -6 -6  6  6  6  6  6  6  6  6]


In [31]:
# 1.k. 
k = np.random.random(10)
np.sort(k)

array([0.0136598 , 0.06339851, 0.24843313, 0.41767248, 0.50932176,
       0.56646483, 0.59377543, 0.72605662, 0.81819965, 0.92571699])

In [32]:
# 1.l. Consider two random array A anb B, check if they are equal
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(np.array_equal(A,B))
print(A)
print(B)

False
[1 1 1 0 0]
[0 0 1 1 1]


In [33]:
# 1.m. How to convert an integer (32 bits) array into a float (32 bits) in place?
Z = np.arange(10, dtype=np.int32)
print(Z.dtype)
Z = Z.astype(np.float32)
print(Z.dtype)

int32
float32


In [34]:
# 1.n. How to get the diagonal of a dot product?
A = np.arange(9).reshape(3,3)
B = A + 1
C = np.dot(A,B)
D = ...
print(C)

[[ 18  21  24]
 [ 54  66  78]
 [ 90 111 132]]
